core:
  options:
    naming-scheme: '{name}/{version}'
    compiler: gcc@5.3.0
    arch: linux-SuSE11-x86_64
  packages:
    libelf:
      libelf@0.8.13: ~
    git:
      git@2.9.3: ~
    tmux:
      tmux@2.2: ~
    vim:
      vim@8.0: ~

